### ISSUE TITLE
Policy commands

### ISSUE THREAD

**Issue by InbalZilberman** [cyberark/conjur-api-python3#112]
## **Feature Overview & Customer Need**

**As a**  Conjur user 
**I would like to** use the conjur cli 
**In order to** manage policy in Conjur

**As a**  Conjur user 
**I would like to** use the conjur cli 
**In order to** create update and delete Conjur's resources

We will use 3 sub commands
* load - load a policy and create resource that were not defined before. Create mode. Wraps [POST API](https://docs.cyberark.com/Product-Doc/OnlineHelp/AAM-DAP/Latest/en/Content/Developer/Conjur_API_Append_Policy.htm2)
* replace - Fully replace of the existing policy, deleting any data that is not declared in the new policy. Wraps [PUT API](https://docs.cyberark.com/Product-Doc/OnlineHelp/AAM-DAP/Latest/en/Content/Developer/Conjur_API_Replace_Policy.htm)
* update -  Update an <u>existing</u> resource in a policy, The resource may be explicitly deleted or changed using the !delete, !revoke, and !deny statements. Unlike “replace” mode, resources that are not in the policy are not implicitly deleted. Wraps [PATCH API](https://docs.cyberark.com/Product-Doc/OnlineHelp/AAM-DAP/Latest/en/Content/Developer/Conjur_API_Update_Policy.htm)
remark also new resource can be define

The commands will be used as follow:

conjur [global options] policy **load** -f < policy file name > -b < branch name>
conjur [global options] policy **replace** -f < policy file name > -b < branch name>
conjur [global options] policy **update** -f < policy file name > -b < branch name>

Args description:

-b --branch <Branch name> - provide the policy name/identifier under which the file will be loaded. Provide the policy branch name

-f --file <Policy file name>  - provide the file name of the policy

Corresponding command in Ruby CLI
| Python  | Ruby           |
| ------- | -------------- |
| load    | load           |
| replace | load --replace |
| update  | load --delete  |
Expected behavior should not change from the corresponding command in Ruby CLI **except for update**. In update we will provide a we will present a message recommend load or replace for creating new resources @sharonr78 to fill in
Any response provided today should remain the same.
Common use case is getting from the response the API Keys of resources.

Help is according to https://ljfz3b.axshare.com/#id=s9nycf&p=conjur_help__policy&g=1

## Quality

Make sure we have test coverage of the policy commands.  Create test plan and execute accordingly.

## Process logic and Demo

Conjur use with a' machine that the Python CLI already been installed and conjur init run

given a file name "myPolicy.yaml"

    - !policy
      id: azure-apps
      body:
        - !group
        - &hosts
          - !host
            id: azureVM
            annotations:
              authn-azure/subscription-id: subscr1pt10n-1dmy-subsc-r1pt10n1d
              authn-azure/resource-group: myResourceGroup
              authn-azure/system-assigned-identity: 0000aaaa-00aa-00aa-00aa-00000aaaaa
    
    - !grant
      role: !group
      members: *hosts

One runs

         conjur policy load -f myPolicy.yaml -b root 

as a result host myapp got API Key      

{

  "created_roles": {

​    "default:host:azure-apps/azureVM": {

​      "id": "default:host:azure-apps/azureVM",

​      "api_key": "c1h1v83tqv3zz2b0q60s2znv4xw3s2t6981phakxf1058gd7t4t58f"

​    }

  },

  "version": 8

}

Now create a file called replace.yaml with

```
- !policy
  id: azure-apps
  body:
    - !group
    - &hosts
      - !host
        id: azureVM
        annotations:
          authn-azure/subscription-id: subscr1pt10n-1dmy-subsc-r1pt10n1d
          authn-azure/resource-group: myResourceGroup
          authn-azure/user-assigned-identity: user-id #replaced
    
      - !host 
         id: myapp2
         annotations:
          authn-azure/subscription-id: subscription-id
          authn-azure/resource-group: resource-group
          
    - !grant
      role: !group
      members: *hosts



```

`conjur policy replace -f replace.yaml -b root

As a result hosts  myapp2 got API Key

{

  "created_roles": {

​    "default:host:azure-apps/myapp2": {

​      "id": "default:host:azure-apps/myapp2",

​      "api_key": "2t6fs8asp5bzd9qbjh23eekhfdhsa6b419dtt0kmb5rab2qwkbr4"

​    }

  },

  "version": 2

}

now create a file called update.yaml with

```yaml
- !delete
 record: !host myapp1



 - !host #UPDATED`
 id: myapp2
 annotations:
 authn-azure/subscription-id: subscription-id
 authn-azure/resource-group: resource-group
 authn-azure/user-assigned-identity: user-id #ADDED
```

one run

`conjur policy update update.yaml azure-apps  `

As a result host myapp2 got API Key and my app is deleted      

{

  "created_roles": {},

  "version": 1

}

Demo each option that was implemented

## User messages

All user messages regarding policy actions should be reviewed again

Especially error messages 

if an argument is missing we need to return the help of the command 

After update command we will present a message recommend load or replace for creating new resources .... @sharonr78 to fill in

## **Documentation**

Please provide enhance documentation in online help and readme

## DOD

- [ ] Implement the policy's commands Conjur Python CLI in all 3 platforms
- [ ] Demo the flow described above
- [ ] Automatic integration tests written according to a test plan and passed successfully
- [ ] Fill in the user messages - link to a page with all user messages for CLI saved and reviewed. 
- [ ] Fill in the logs and place here a link to the logs files - link to a page with all logs for CLI saved and reviewed. 
- [ ] Logs were reviewed by TW and PO
- [ ] Are there new Audits to this feature? If so please document them and provide here a link (N/A)
